language: python
sudo: false
python:
 - "2.7"
env:
 - DJANGO_VERSION=1.7.3
 - DJANGO_VERSION=1.8
install:
 - pip install pep8 pyflakes coverage python-coveralls
 - pip install -q Django==$DJANGO_VERSION
 - python setup.py install
script:
 - pep8 calaccess_campaign_browser
 - pyflakes calaccess_campaign_browser
 - coverage run setup.py test
after_success:
 - coveralls
